### PR TITLE
Refactor: Improve font configurations

### PR DESCRIPTION
**Pull request by uskayyyyy**
## Overview

This PR improves the font configurations according to the [Next.js official document](https://nextjs.org/docs/app/building-your-application/optimizing/fonts). Since we use Tailwind CSS, this PR also configures the fonts in `tailwind.config.ts` to utilize the fonts using Tailwind classes.

## Changes
- Moved `src/const/fonts/fonts.ts` to `src/const/fonts.ts`
- Removed the unnecessary fonts from `fonts.ts`
- Added `fontFamily` to `tailwind.config.ts`
- Applied the project's default font, `Outfit` to using the Tailwind CSS class.

## Review points

- 

## Screen Captures

src/app/layout.tsx
```tsx
<html lang="en" className={fontOutfit.variable} suppressHydrationWarning>
```
This line generates the CSS variable of the font:

image

<br>

src/app/layout.tsx
```tsx
<body className={cn('min-h-screen bg-primary-lightest antialiased font-outfit')}>
```

The font class created by Tailwind is available:

Screenshot 2023-12-19 at 13 11 33

<br>

The font style works:

https://github.com/genesis-tech-tribe/nishiki-frontend/assets/99148565/7213c3f8-7eb9-4a70-9094-750dff614f38

## Note

- You can find the font files in the `.next/static/media/` directory, meaning it's optimized, not downloaded on the client side.

## Assignee Checklist:

- [x] The base branch is correct (See: [Types of Branches](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [x] The branch name follows the [Branch Naming Conventions](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [x] The correct assignees and reviewers have been designated for this PR
- [x] The coding style follows the [Coding Style Guide](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [x] All the related issues are associated with this PR
- [x] All criteria in the associated issues are met (please tick the checkboxes)
- [x] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [x] The code follows the generic best practices and our [Coding Style Guide](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [x] Code is well-commented and easy to understand
- [x] UI changes accurately reflect the provided design

### CODE REVIEW

**Review by kotaaaa — APPROVED** [review]
I could't add any comment, thank you-

**Comment by uskayyyyy** [comment]
@kotaaaa Thank you for your review! Could you tick the reviewer checklist, please?

**Comment by kanta1207** [comment]
LGTM, too! Sorry for the late review!

**Comment by uskayyyyy** [comment]
@kotaaaa @kanta1207 
Thank you for your reviews!

**Pull request merged**
