### PR TITLE
Refactor: Refactor directory structure of the foods-feature-specific components

### PR DESCRIPTION
**Pull request by uskayyyyy**
## Overview

This PR refactors the directory structure of the foods-feature-specific components.

## Changes

- Organized the `Form/` (previous `AddEditForm/`) directory
- Created `BadgeList/` directory and put all the child components in there
- Created `FilterButton/` directory and put all the child components in there
- Did not change any existing code except the `import` and `export` lines

## Screen Captures

The directory structure ended up as follows:

image

## Note

-

## Assignee Checklist:

- [x] The base branch is correct (See: [Types of Branches](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [x] The branch name follows the [Branch Naming Conventions](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [x] The correct assignees and reviewers have been designated for this PR
- [x] The coding style follows the [Coding Style Guide](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [x] All the related issues are associated with this PR
- [x] All criteria in the associated issues are met (please tick the checkboxes)
- [x] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] Code is well-commented and easy to understand
- [ ] UI changes accurately reflect the provided design

### CODE REVIEW

**Review by kanta1207 — APPROVED** [review]
The size of PR was really nice and easy to review, again!

**Review by kanta1207 — CHANGES_REQUESTED** [review]
Thank you for the refactor!
Directory structure overall seemed to be great.

Could you check my comment on tiny thing, and please fix it if it suits with your idea!

**Comment by uskayyyyy** [comment]
@kanta1207 
Thank you for your comments. They were all my mistakes, haha. Please review them since I fixed them.

By the way, your reviews are never nitpicky at all! I am so happy to listen to your feedback 😊
Also, I believe that giving feedback to each other will ultimately improve the efficiency of the team, although it looks like it delays the development at that point.
So, please always feel free to share whatever your concerns and suggestions!

**Review by kanta1207 — APPROVED** [review]
Thank you for your comment and fixing it!

I'll keep trying not to hesitate and to give good feedbacks as you and Kota do 👍

**Review by kotaaaa — APPROVED** [review]
Thank you for your work! (Sorry for that I cannot find any potential suggestion..)

**Comment by uskayyyyy** [comment]
@kanta1207 @kotaaaa 
Thank you for your reviews!

**Pull request merged**
