### PR TITLE
Organizing the `features/` directory

### PR DESCRIPTION
**Pull request by uskayyyyy**
## Overview

Organized the sub-directories of the `src/features/` directory based on the [discussion](https://github.com/orgs/genesis-tech-tribe/discussions/78).

## Changes
- Removed the unnecessary feature directories
	- `container/`
	- `user/`
- Added necessary feature directories
	- `foods/`
	- `profile/`
	- `auth/`
- Pluralize the `group/` directory into `groups/`

### CODE REVIEW

**Comment by kotaaaa** [comment]
Thank you for your updates.
What is the difference between `profile/` and `user/`?

**Comment by uskayyyyy** [comment]
@kotaaaa
> What is the difference between profile/ and user/?

I don't know what Kanta intended when he created `user/`.

My intention is to match feature directories with the bottom nav bar.

image

**Comment by kanta1207** [comment]
> @kotaaaa
> 
> > What is the difference between profile/ and user/?
> 
> I don't know what Kanta intended when he created `user/`.
> 
> My intention is to match feature directories with the bottom nav bar.
> 
> image

Sorry guys, creating "/user" route was just my mistake, and it's better to use "/profile" route.

**Review by kotaaaa — APPROVED** [review]
Sorry for late. Approved

**Review by kotaaaa — APPROVED** [review]

**Pull request merged**
